# ~/.config/starship.toml

# Use custom format
format = """
$line_break\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$env_var\
$line_break\
$status\
$character"""

right_format = """
$docker_context\
$dart\
$java\
$kotlin\
$lua\
$nodejs\
$python\
$line_break\
$cmd_duration\
$time"""

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Inserts a blank line between shell prompts
add_newline = false

# Replace the "‚ùØ" symbol in the prompt with "‚ûú"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[Œª](bold gray)"     # The "success_symbol" segment is being set to "‚ûú" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[username]
style_user = "purple bold"
style_root = "red bold"
format = "[$user]($style)@"
disabled = false
show_always = true

[hostname]
ssh_only = false
format =  "[$hostname](bold yellow): "
disabled = false

[directory]
style = "bold blue"
truncate_to_repo = false
truncation_length = 8
truncation_symbol = "‚Ä¶/"

[time]
style = "green"
disabled = false
format = '[\[$time\]]($style)'
time_format = "%T"
utc_time_offset = "+3"

[cmd_duration]
min_time = 500
format = "[$duration](bold yellow) "

[status]
style = "bg:red black"
format = '[\[$common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = false
disabled = false

[git_commit]
commit_hash_length = 4
tag_symbol = "üîñ "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[üçí PICKING](bold red)"

[git_metrics]
added_style = "bold blue"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[git_status]
ahead = "‚á°${count}"
diverged = "‚áï‚á°${ahead_count}‚á£${behind_count}"
behind = "‚á£${count}"

