# ~/.config/starship.toml

format = """
$line_break\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$git_metrics\
$hg_branch\
$env_var\
$line_break\
$status\
$character"""

right_format = """
$line_break\
$cmd_duration\
$time"""

scan_timeout = 10
add_newline = false

[character]
success_symbol = "[λ](bold grey)"
error_symbol = "[x](bold red)"

[username]
style_user = "purple bold"
style_root = "red bold"
format = "[$user]($style)@"
disabled = false
show_always = true

[hostname]
ssh_only = false
format =  "[$hostname](bold yellow): "
disabled = false

[directory]
style = "bold blue"
truncate_to_repo = false
truncation_length = 8
truncation_symbol = "…/"

[time]
style = "green"
disabled = false
format = '[\[$time\]]($style)'
time_format = "%T"
utc_time_offset = "+3"

[cmd_duration]
min_time = 500
format = "[$duration](bold yellow) "

[status]
style = "bg:red black"
format = '[\[$common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = false
disabled = false

[git_branch]
style = "green"
format = "[$branch]($style) "

[git_commit]
commit_hash_length = 4
tag_symbol = "tag"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_metrics]
added_style = "green"
deleted_style = "red"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '
disabled = false

[git_status]
format = '([$all_status$ahead_behind](218) )'
disabled = false
